version: '3'
services:
  ngnix:
    image: nginx:1.21.0-alpine
    container_name: proxy
    volumes:
      - /root/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - apps

  wordpress:
    image: wordpress:php7.4-apache
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=${rds_endpoint}
      - WORDPRESS_DB_USER=${rds_user}
      - WORDPRESS_DB_PASSWORD=${rds_password}
      - WORDPRESS_DB_NAME=${rds_db}
      - WORDPRESS_TABLE_PREFIX=wp
    networks:
      - apps

networks:
  apps:
    driver: bridge